### ISSUE TITLE
Issue with Links?

### ISSUE THREAD

**Issue by mmcky** [QuantEcon/lecture-stats#1]
@HumphreyYang I think there may be an issue with some links?

```
/__w/lecture-stats/lecture-stats/lectures/exchangeable.md:37: WARNING: unknown document: odu
writing output... [100%] zreferences                                           
/__w/lecture-stats/lecture-stats/lectures/exchangeable.md:37: WARNING: unknown document: mccall_model
/__w/lecture-stats/lecture-stats/lectures/exchangeable.md:44: WARNING: unknown document: odu
/__w/lecture-stats/lecture-stats/lectures/likelihood_bayes.md:44: WARNING: unknown document: odu
/__w/lecture-stats/lecture-stats/lectures/likelihood_bayes.md:816: WARNING: unknown document: odu
/__w/lecture-stats/lecture-stats/lectures/likelihood_ratio_process.md:691: WARNING: unknown document: odu
/__w/lecture-stats/lecture-stats/lectures/multivariate_normal.md:1967: WARNING: unknown document: kalman
/__w/lecture-stats/lecture-stats/lectures/multivariate_normal.md:2133: WARNING: unknown document: svd_intro
/__w/lecture-stats/lecture-stats/lectures/wald_friedman.md:466: WARNING: unknown document: optgrowth
```

**Comment by HumphreyYang** [comment]
Hi @mmcky,

Many thanks for raising this issue.

I haven’t established redirects across series. These links are directed to outside of this series.

Other series will have the same issue as well.

I will work on establishing those links next week.

**Comment by mmcky** [comment]
Thanks @HumphreyYang 

[35a24a6](https://github.com/QuantEcon/lecture-stats/commit/35a24a64a2f5b94c746c7c5d46b1b559d65f2cdd) fixes the issue.

**Comment by HumphreyYang** [comment]
> Thanks @HumphreyYang
> 
> [35a24a6](https://github.com/QuantEcon/lecture-stats/commit/35a24a64a2f5b94c746c7c5d46b1b559d65f2cdd) fixes the issue.

Many thanks @mmcky,

I noticed that AR(1) was not assigned to a destination series. I have proposed to migrate AR(1) lecture to the intro series.

Since AR(1) has been referenced in many series, I will go through series that did not reference the AR(1) lecture first.

Please refrain from publishing this on the official URL before this issue is resolved.

Many thanks in advance.
