### ISSUE TITLE
[bayes_nonconj] Migrate from pytorch to just use JAX

### ISSUE THREAD

**Issue by mmcky** [QuantEcon/lecture-stats#13]
The lecture `bayes_conconj` uses `pytorch`. This causes software issues between `pytorch` and `jax` as they don't reference the same CUDA and CUDANN drivers or version. They are not compatible with each other in the same software context for CUDA v12. 

https://github.com/google/jax/issues/18032

Is it feasible to update this lecture to only use JAX and remove `pytorch` as a dependency? It is the only lecture to use `pytorch` 

- [x] remove `torch` as a dependency
- [ ] remove `pyro` as a dependency

@kp992 would you be able to look into this?

--- 

## Infrastructure Updates:

- [x] update from `cuda-11.8.0-anaconda-2023-09-py311` to `cuda-12.3.1-anaconda-2023-09-py311`
- [ ] lower cloud `hdd` from `100` to `40` GB

**Comment by HumphreyYang** [comment]
Many thanks @mmcky and @kp992,

The main dependency is [tfp.distributions.TransformedDistribution](https://www.tensorflow.org/probability/api_docs/python/tfp/distributions/TransformedDistribution) used to generate transformed distributions.

**Comment by mmcky** [comment]
thanks @HumphreyYang let me know if you think this is feasible.

**Comment by kp992** [comment]
Hi @mmcky and @HumphreyYang, I was checking the `pyro` docs (http://pyro.ai/#install) and it uses`pytorch`([see](https://github.com/pyro-ppl/pyro/blob/df34383cfe8144234c0b24a212464531883eaf6e/setup.py#L105)) in the backend which means to remove pytorch dependency completely, we also need to remove `pyro` from the this lecture. I think this lecture has both `pyro` and `numpyro` doing the same job and so probably we can remove it. Also, from their docs page:

"""
NumPyro Release We’re excited to announce the release of [NumPyro](https://github.com/pyro-ppl/numpyro), a NumPy-backed Pyro using [JAX](https://github.com/google/jax) for automatic differentiation and JIT compilation, with over 100x speedup for HMC and NUTS! See the [examples](http://pyro.ai/numpyro) and [documentation](https://num.pyro.ai/) for more details.
"""

So, the summary is if we want to remove `torch`, we might also need to remove `pyro`. This would make this lecture use JAX backed `numpyro` everywhere.

**Comment by mmcky** [comment]
thanks @kp992 -- numpyro is also used elsewhere and I have been able to install that with `numpyro[cuda]` in the backend.

**Comment by kp992** [comment]
So do we want to remove `pyro` from this lecture?

**Comment by mmcky** [comment]
> So do we want to remove `pyro` from this lecture?

Yes. I just did a check and it is also only used in [bayes_nonconj] so removing it would be great. 👍
