### ISSUE TITLE
[bayes_nonconj] Exection speed 4 x faster on EC2

### ISSUE THREAD

**Issue by mmcky** [QuantEcon/lecture-stats#3]
@HumphreyYang I noticed `bayes_nonconj` went from 4000+ to 1000s to run. 

https://quantecon.github.io/lecture-stats/status.html

This is likely due to `EC2` and `V100 GPUs` but if you could take a look at the lecture to verify it that would be great. 

Thanks.

**Comment by HumphreyYang** [comment]
Hi @mmcky,

The build looks good to me. I think it is mainly due to the GPU access. 

We also got rid of warnings in the lecture about falling back to CPUs.

Please feel free to close this issue.
